name: baztami
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_riverpod: ^2.5.1
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  fl_chart: ^0.68.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.2
  riverpod: ^2.5.1
  shared_preferences: ^2.5.3
  image_picker: ^1.0.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  record: ^5.1.2
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2
  state_notifier: ^1.0.0
  flutter_slidable: ^4.0.3
  elevenlabs_flutter_updated: ^0.0.1
  audioplayers: ^6.5.1
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
